//Teste de requisição

@baseURL =  http://localhost:4001
@id = 
###
// GET - Listar os Cadastros
GET {{baseURL}}/cadastros
content-Type: application/json

###
// GET - Listargem do cadastro pelo id
GET {{baseURL}}/cadastros/{{id}}
content-Type: application/json

###
// POST - Incluir um novo cadastro
POST  {{baseURL}}/cadastros
content-Type: application/json



###
// DELETE  - Apagar um cadastro
DELETE {{baseURL}}/cadastros/{{id}}
content-Type: application/json

###
// PUT - Atualizar um cadastro
PUT  {{baseURL}}/cadastros
content-Type: application/json